# _config.yml

title: Your Personalized Website
description: Explore and learn more about me.

theme: minima # You can replace this with the name of your preferred theme

author:
  name: Your Name

# Social media links (customize as needed)
social:
  - title: GitHub
    url: https://github.com/your-username
  - title: Twitter
    url: https://twitter.com/your-twitter-handle
  # Add more social links if needed

# Navigation links (customize as needed)
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  # Add more navigation links if needed

# GitHub Pages settings
remote_theme: "username/repo" # Replace with your GitHub Pages theme repository

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
